data:
  train_path: 'data/processed/train.csv'
  test_size: 0.2
  random_state: 42
  processed_path: 'data/processed/'
mlflow:
  tracking_uri: 'mlruns'
  experiment_name: 'Churn Prediction Experiment v11'
modelling:
  n_iter: 20
  features:
    - 'gender'
    - 'Partner'
    - 'Dependents'
    - 'tenure'
    - 'InternetService'
    - 'OnlineSecurity'
    - 'OnlineBackup'
    - 'DeviceProtection'
    - 'TechSupport'
    - 'StreamingTV'
    - 'StreamingMovies'
    - 'Contract'
    - 'PaymentMethod'
    - 'MonthlyCharges'
    - 'TotalCharges'
    - 'QtdProducts'
  target: 'Churn'